# ¿Qué hace felices a los países?
## Análisis exploratorio de los factores que explican la felicidad mundial en 2024

### Introducción
La felicidad de una población es un concepto complejo en el que influyen factores económicos, sociales, políticos y de salud. En los últimos años, diferentes informes internacionales han intentado medir este bienestar subjetivo para entender por qué algunos países muestran niveles de satisfacción vital más altos que otros.

En este proyecto se realizará un Análisis Exploratorio de Datos (EDA) a partir de un dataset internacional sobre felicidad, centrando el estudio en los datos correspondientes al año 2024. El objetivo no será solo describir qué países ocupan las primeras y últimas posiciones del ranking, sino también identificar qué variables parecen estar más relacionadas con un mayor nivel de felicidad.

A través de este análisis se buscará detectar patrones, comparar comportamientos entre países y extraer conclusiones útiles sobre los principales factores asociados al bienestar. De esta forma, el proyecto combinará una parte descriptiva con una interpretación orientada a negocio y toma de decisiones.

### Objetivo general
Analizar los datos de felicidad mundial de 2024 para identificar qué factores sociales, económicos y de calidad de vida están más relacionados con la puntuación de felicidad de los países, detectando patrones relevantes y diferencias entre los países con mejores y peores resultados.

### Hipótesis
1. Los países con mayor PIB per cápita tienden a presentar mayores niveles de felicidad.

2. El apoyo social es uno de los factores más influyentes en la felicidad de un país.

3. Una mayor esperanza de vida saludable está asociada con una mayor puntuación de felicidad.

4. Los países con mayor libertad para tomar decisiones vitales tienden a mostrar niveles más altos de felicidad.

5. Los países con mayores niveles de felicidad no destacan únicamente en una sola variable, sino en la combinación de varios factores favorables, como un mayor PIB per cápita, un fuerte apoyo social y una mejor esperanza de vida saludable.

In [1]:
import pandas as pd

df = pd.read_csv('../src/data/happiness.csv')

df.head()

,Year,Rank,Country name,Ladder score,upperwhisker,lowerwhisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,2024,1,Finland,7.736,7.810,7.662,1.749,1.783,0.824,0.986,0.110,0.502,1.782
1,2023,143,Afghanistan,1.721,1.775,1.667,0.628,0.000,0.242,0.000,0.091,0.088,0.672
2,2022,137,Afghanistan,1.859,1.923,1.795,0.645,0.000,0.087,0.000,0.093,0.059,0.976
3,2021,146,Afghanistan,2.404,2.469,2.339,0.758,0.000,0.289,0.000,0.089,0.005,1.263
4,2020,150,Afghanistan,2.523,2.596,2.449,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [3]:
df.shape

(1969, 13)

In [4]:
df.columns

Index(['Year', 'Rank', 'Country name', 'Ladder score', 'upperwhisker',
       'lowerwhisker', 'Explained by: Log GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='str')

In [ ]:
"""
Data Filtering

The dataset has been filtered to work only with the year 2024, in order to simplify the analysis and focus it on the most current situation available.

The resulting dataset contains information from 147 countries and retains all variables relevant to the analysis.

"""

df_2024 = df[df['Year'] == 2024]

df_2024.shape

(147, 13)

In [8]:
df_2024.head()

,Year,Rank,Country name,Ladder score,upperwhisker,lowerwhisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,2024,1,Finland,7.736,7.810,7.662,1.749,1.783,0.824,0.986,0.110,0.502,1.782
13,2024,2,Denmark,7.521,7.611,7.431,1.825,1.748,0.820,0.955,0.150,0.488,1.535
26,2024,3,Iceland,7.515,7.606,7.425,1.799,1.840,0.873,0.971,0.201,0.173,1.659
45,2024,4,Sweden,7.345,7.427,7.262,1.783,1.698,0.889,0.952,0.170,0.467,1.385
58,2024,5,Netherlands,7.306,7.372,7.240,1.822,1.667,0.844,0.860,0.186,0.344,1.583

In [11]:
df_2024.info()

<class 'pandas.DataFrame'>
Index: 147 entries, 0 to 1956
Data columns (total 13 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Year                                        147 non-null    int64
 1   Rank                                        147 non-null    int64
 2   Country name                                147 non-null    str
 3   Ladder score                                147 non-null    float64
 4   upperwhisker                                147 non-null    float64
 5   lowerwhisker                                147 non-null    float64
 6   Explained by: Log GDP per capita            147 non-null    float64
 7   Explained by: Social support                147 non-null    float64
 8   Explained by: Healthy life expectancy       146 non-null    float64
 9   Explained by: Freedom to make life choices  146 non-null    float64
 10  Explained by: Generosity                    147 non-null    float64
 11  Explained by: Perceptions of corruption     146 non-null    float64
 12  Dystopia + residual                         144 non-null    float64
dtypes: float64(10), int64(2), str(1)
memory usage: 16.1 KB

In [12]:
df_2024.describe()

,Year,Rank,Ladder score,upperwhisker,lowerwhisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
count,147.0,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,146.000000,146.000000,147.000000,146.000000,144.000000
mean,2024.0,74.000000,5.578170,5.688701,5.467612,1.318701,1.333395,0.551493,0.749253,0.113442,0.146815,1.368819
std,0.0,42.579338,1.158278,1.148881,1.168702,0.393862,0.349952,0.218802,0.177694,0.059773,0.113880,0.521585
min,2024.0,1.000000,1.364000,1.427000,1.301000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.099000
25%,2024.0,37.500000,4.702500,4.828500,4.576500,1.037000,1.131000,0.414500,0.655000,0.066500,0.066500,1.103000
50%,2024.0,74.000000,5.868000,5.965000,5.747000,1.347000,1.438000,0.550500,0.767000,0.111000,0.118000,1.387000
75%,2024.0,110.500000,6.479000,6.570000,6.375000,1.648000,1.593500,0.713250,0.881250,0.150500,0.184500,1.678000
max,2024.0,147.000000,7.736000,7.810000,7.662000,2.028000,1.840000,0.948000,1.018000,0.323000,0.522000,2.701000

In [13]:
df_2024.isnull().sum()

Year                                          0
Rank                                          0
Country name                                  0
Ladder score                                  0
upperwhisker                                  0
lowerwhisker                                  0
Explained by: Log GDP per capita              0
Explained by: Social support                  0
Explained by: Healthy life expectancy         1
Explained by: Freedom to make life choices    1
Explained by: Generosity                      0
Explained by: Perceptions of corruption       1
Dystopia + residual                           3
dtype: int64